---
services:
  watertap-backend:
    image: ${IMAGE_NAME}-backend:${BRANCH_NAME}
    container_name: ${SERVICE_NAME}-${BRANCH_NAME}-backend
    restart: unless-stopped
    environment:
      JWT_ALGORITHM: "${JWT_ALGORITHM}"
      JWT_EXPIRES_IN: "${JWT_EXPIRES_IN}"
      JWT_SECRET: "${JWT_SECRET}"
      MONGODB_URL: "mongodb+srv://emXjupbD:nlLXRCzb9GDKXXdU@us-east-1.ufsuw.mongodb.net/my-mongo-db-5qUf"
      BOT_TOKEN: "${BOT_TOKEN}"
      BOT_NAME: "${BOT_NAME}"
      NODE_ENV: "${NODE_ENV}"
      APP_URL: "https://api.${PROJECT_URL}"
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE_NAME}-${BRANCH_NAME}-backend.entrypoints=websecure
      - traefik.http.routers.${SERVICE_NAME}-${BRANCH_NAME}-backend.rule=Host(`api.${PROJECT_URL}`)
      - traefik.http.routers.${SERVICE_NAME}-${BRANCH_NAME}-backend.tls=true
      - traefik.http.routers.${SERVICE_NAME}-${BRANCH_NAME}-backend.tls.certresolver=letsencrypt
      - traefik.http.services.${SERVICE_NAME}-${BRANCH_NAME}-backend.loadbalancer.server.port=3002
    networks:
      - traefik

  watertap-frontend:
    image: ${IMAGE_NAME}-frontend:${BRANCH_NAME}
    container_name: ${SERVICE_NAME}-${BRANCH_NAME}-frontend
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.${SERVICE_NAME}-${BRANCH_NAME}-frontend.entrypoints=websecure
      - traefik.http.routers.${SERVICE_NAME}-${BRANCH_NAME}-frontend.rule=Host(`app.${PROJECT_URL}`)
      - traefik.http.routers.${SERVICE_NAME}-${BRANCH_NAME}-frontend.tls=true
      - traefik.http.routers.${SERVICE_NAME}-${BRANCH_NAME}-frontend.tls.certresolver=letsencrypt
      - traefik.http.services.${SERVICE_NAME}-${BRANCH_NAME}-frontend.loadbalancer.server.port=4173
    networks:
      - traefik

networks:
  traefik:
    external: true