name: se7en-drinks
region: us-east-1
yamlVersion: 2
services:
  databases:
    - name: my-mongo-db
      type: mongo-atlas

nestjs:
  path: backend
  packageManager: npm
  scripts:
    deploy:
      - npm ci
      - npm run build
      - npm run prepare-deploy
    build:
      - npm run build
    start:
      - node dist/main.js
  environment:
    MONGODB_URL: ${{ my-mongo-db.url }}

frontend:
  path: frontend
  publish: dist
  scripts:
    deploy:
      - pnpm install
    build:
      - pnpm run build
    start:
      - pnpm install
      - pnpm run dev
  environment:
    VITE_API_URL: ${{ nestjs.url }}
  subdomain: amaranth-available-blackbird
