name: se7en-drinks
region: us-east-1
yamlVersion: 2
services:
  databases:
    - name: my-mongo-db
      type: mongo-atlas

nestjs:
  path: backend
  packageManager: pnpm # Use pnpm consistently
  timeout: 30 # Add this line
  scripts:
    deploy:
      - npm ci
    build:
      - pnpm install --frozen-lockfile
      - pnpm run build
    start:
      - pnpm run start:prod # Remove pnpm install from start!
  environment:
    MONGODB_URL: ${{ my-mongo-db.url }}

frontend:
  path: frontend
  publish: dist
  scripts:
    deploy:
      - npm install
    build:
      - npm run build
    start:
      - npm run dev
  environment:
    VITE_API_URL: ${{ nestjs.url }}
  subdomain: amaranth-available-blackbird
